### ISSUE TITLE
Global access to Rake DSL methods is deprecated / No admin login

### ISSUE THREAD

**Issue by jvenator** [hulihanapplications/Opal#7]
Upon running the following line in Terminal...

`$ rake opal:install RAILS_ENV=production LOCALE=en`

I get this...

`WARNING: Global access to Rake DSL methods is deprecated.  Please include...  Rake::DSL into classes and modules which use the Rake DSL methods. WARNING: DSL method Opal::Application#task called at /Users/username/.rvm/gems/ruby-1.9.2-head@rails3/gems/railties-3.0.3/lib/rails/application.rb:214:in `initialize_tasks'`

It then proceeds to run the rake command in its entirety as best I can tell. I recall you updating to Rails 3.0.7, but have no idea if that's related. I then rename the 'database.yml.default' file to 'database.yml' and launch webrick specifying the production database. I am then able to view the application in my browser on the localhost. However, when I attempt to login with admin/admin I am unable to. It generates a red ajax message saying "You must be logged in to do this." as well as a green message right below it saying "Your original destination has been saved. Please log in to continue."

This is a local cloned install from my forked Opal/master repository.

**Comment by hulihanapplications** [comment]
Both of these issues are currently fixed in the dev branch. 

The deprecation warning shouldn't have caused anything to install improperly, your app seems like it installed correctly.  

The login issue you're having is an authlogic bug that fails to populate the default admin account's persistence_token attribute when seeding the database in production mode. I implemented a fix in commit: [956352](https://github.com/hulihanapplications/Opal/commit/9563523fa819b1bd3b14c07011c5e99879856e4e). You can also fix this through the rails console, like so:

```
u = User.find_by_username("admin"); u.save
```

This will assign admin a persistence token and let you log in properly. 

Opal 0.7.3 will be released pretty soon, and these changes will be merged with master. Thanks for keeping an eye out for bugs and reporting them, let me know if you see anything else weird.

**Comment by jvenator** [comment]
Attempted the quick fix via console, but it didn't work.

`Loading development environment (Rails 3.0.3)
ruby-1.9.2-head :001 > User.find_by_username("admin").save
NoMethodError: undefined method `save' for nil:NilClass
from /Users/user/folder/Opal/vendor/bundle/ruby/1.9.1/gems/activesupport-3.0.3/lib/active_support/whiny_nil.rb:48:in `method_missing' from (irb):1
from /Users/user/folder/Opal/vendor/bundle/ruby/1.9.1/gems/railties-3.0.3/lib/rails/commands/console.rb:44:in `start'
from /Users/user/folder/Opal/vendor/bundle/ruby/1.9.1/gems/railties-3.0.3/lib/rails/commands/console.rb:8:in `start'
from /Users/user/folder/Opal/vendor/bundle/ruby/1.9.1/gems/railties-3.0.3/lib/rails/commands.rb:23:in `<top (required)>'
from script/rails:6:in `require'
from script/rails:6:in `<main>'`

Running the same command without `.save` results in a nil value. Is it supposed to be Ruby 1.9.1?

**Comment by hulihanapplications** [comment]
Erg, sorry try this one instead: 

```
u = User.first; u.save
```

**Comment by jvenator** [comment]
Took a couple variations to get it to work. Ultimately had to run `rake db:reset` answering "Y" to populating the sample data, then find and save the first user within console as you instructed above, then run `rake db:migrate`.

Attempting it without one or both of db:reset and db:migrate was not successful. Anyway, I'm in now! Thanks for the responses.
